### ISSUE TITLE
Not a circle on Android after RN version  0.45.0-rc.0

### ISSUE THREAD

**Issue by EyreGe** [genexu/react-native-pie-chart#10] opened 2017-06-20 08:11 UTC
![5ed6189f8c1d0e826104ca1c74fd88aa](https://user-images.githubusercontent.com/19946413/27323161-2bf4579e-55d3-11e7-8dd1-d4e64b56925a.jpg)

**Comment by genexu** [comment] 2017-06-20 11:25
Hello @EyreGe, can you give me the props you input and package dependencies (or more), i need more information to check up this issue.

**Comment by genexu** [comment] 2017-06-23 14:04
Because of there are no further comment, i decided to close this issue, if have any question or similar problem, plz give me a notice.

**Comment by andrii-yarmola** [comment] 2017-06-28 13:04
same issue for android only (its ok for IOS)
i used your examples
"react-native": "0.45.1",
npm 4.2.0
node 7.10.0

**Comment by genexu** [comment] 2017-06-29 13:36
@andrii-yarmola i already verify this is an issue and working on to fix it, thanks for your report.

**Comment by genexu** [comment] 2017-06-29 17:04
[Update] already confirm previous version (1.0.11) is fine (use https://github.com/genexu/react-native-pie-chart/tree/master/example to testing), also testing back to version 1.0.5 .

At version 1.0.12, i update the React Native dependency version and use PropTypes to Instead of React.PropTypes.

So, the problem probably is on React Native side, it need to take some time to find out the problem is happen on witch RN version.

If your are really need this module feature now, I recommend you to downgrade the RN version before it fixed.

**Comment by genexu** [comment] 2017-06-29 17:08
Any body have this issue, plz share you package dependencies, and have a comment immediately when you discover this issue is be repaired.

**Comment by genexu** [comment] 2017-06-30 14:14
[Update] react-native version check out result

RN 0.45.0 with react@16.0.0-alpha.12 - Bad 
RN 0.45.0-rc.2 with react@16.0.0-alpha.12 - Bad
RN 0.45.0-rc.1 with react@16.0.0-alpha.12 - Bed
RN 0.45.0-rc.0 with react@16.0.0-alpha.12 - Bed
RN 0.44.3 with react@16.0.0-alpha.6 - Good
RN 0.44.0 Good react@16.0.0-alpha.6 - Good

**Comment by danstepanov** [comment] 2017-08-04 08:52
"react-native": "^0.46.1" and have this issue as well

**Comment by genexu** [comment] 2017-08-04 15:47
@danstepanov thx for the report.

**Comment by lelup** [comment] 2017-08-10 04:12
![screen shot 2017-08-10 at 11 09 18](https://user-images.githubusercontent.com/19283388/29154138-7ca9a750-7dbc-11e7-9a76-155a62f789b3.png)
I have same issue on Android, my dependencies : {
  "react": "16.0.0-alpha.12",
   "react-native": "0.46.4",
}.

**Comment by zpp-gp** [comment] 2017-11-29 15:11
如果使用 RN 0.44.3 with react@16.0.0-alpha.6 
采用这个版本1.0.12,Android 是可以正确的吗？

**Comment by genexu** [comment] 2017-11-29 15:14
@zpp-gp That's right, RN 0.44.3 with react@16.0.0-alpha.6 version has been tested as well.

**Comment by zpp-gp** [comment] 2017-11-29 15:17
谢谢，希望有时间可以解决高版本的兼容性问题，顶顶！

**Comment by Selvamhibiz** [comment] 2018-01-03 10:24
@genexu 
My Application is getting closed while using Pie Chart but working fine in ios and my dependencies are 
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-pie-chart": "1.0.12"
  },
i also tried by changing dependencies to  ("RN 0.44.3 with react@16.0.0-alpha.6"
"RN 0.44.0 Good react@16.0.0-alpha.6")  which you had mentioned in earlier comments. 

But for Android it is not working. can you suggest me how to implement Pie Chart in my Project.

**Comment by genexu** [comment] 2018-01-06 07:26
@Selvamhibiz Sorry for late reply, quite busy recently.

So, let me ensure first, your problem is application will be closed when use this package? that is not related with this issue, and i'm haven't this problem before. I need more information about this issue to find solve it.

Thanks for your response.

**Comment by robertobrogi** [comment] 2018-01-09 11:38
Hi,
I use this depen:
"expo": "^23.0.4",
"react": "16.0.0",
"react-native": "0.50.3"

And i have the same problem in Andrios, ios work fine

**Comment by ericrojo156** [comment] 2018-01-28 20:56
I have observed the same issue.
My dependencies are:

		"react": "16.0.0-alpha.12",
		"react-native": "0.49.5",
                "react-native-pie-chart": "~1.0.12"

**Comment by geek6** [comment] 2018-02-05 08:48
i have the same issue on Android, iOS fine.
My dependencies are: 
    "react": "16.0.0",
    "react-apollo": "^2.0.1",
    "react-native": "v0.52.0-rc.0",
    "react-native-pie-chart": "^1.0.12"

**Comment by andreuccia** [comment] 2018-02-07 10:38
same Issue with:

  "react": "16.2.0",
    "react-native": "0.51.0",

**Comment by abbreviatedman** [comment] 2018-03-16 11:26
Not sure if it still helps to get dependencies, but! Same issue with:

"dependencies": {
    "prop-types": "^15.6.0",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-pie-chart": "^1.0.12",
  }

Hope this helps!

**Comment by genexu** [comment] 2018-03-19 02:13
Thanks for everyone who reported the status of this issue, it is always helpful.

RN ART libs seem was not be implement anymore, i'm plan to open another project for RN pie chart with SVG tech (may with other kind of chart, spilt to different module).

Still welcome the status report about this issue, a lot of thanks.

**Comment by skicson** [comment] 2018-03-19 21:41
There is a workaround just for the pie chart - I haven't looked into it enough to figure out how to do the doughnut but looking at https://github.com/bgryszko/react-native-circular-progress/blob/master/src/CircularProgress.js would suggest it's doable.

Anyways, commenting out line 183 of Wedge.js and replacing with 

```javascript
//   return <Shape d={path} stroke={this.props.fill} strokeWidth={outerRadius} strokeCap='butt' />;
let size = this.props.outerRadius * 2;
let cx = cy = size/2;
let p = Path();
p.path.push(0, cx, cy);
p.path.push(4, cx, cy, outerRadius, startAngle * Math.PI / 180, endAngle * Math.PI / 180, 1);
return <Shape d={p} fill={this.props.fill} />;
```
seems to be working so far for me..

**Comment by genexu** [comment] 2018-03-20 03:30
@skicson I was tried the similar code couple month ago, but it's not work. and i just try it again with newest version of RN and React, it work!!! Holy!!!, maybe it was fixed on one of version of RN.

I'm already publish new version of this module, plz update and have a test, thanks again.

If every is good, then i will close this issue.

**Closed as completed** 2018-03-22 02:06 UTC
Labels: help wanted, bug from dependencies
